{"name": "Создание заказа. Неавторизованный пользователь не может создать заказ", "status": "failed", "statusDetails": {"message": "AssertionError: assert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.orders.test_create_orders.TestCreateOrders object at 0x00000205E05E1A00>\ningredients_list = ['61c0c5a71d1f82001bdaaa6d', '61c0c5a71d1f82001bdaaa6f', '61c0c5a71d1f82001bdaaa70', '61c0c5a71d1f82001bdaaa71', '61c0c5a71d1f82001bdaaa72', '61c0c5a71d1f82001bdaaa6e', ...]\n\n    @allure.title('Создание заказа. Неавторизованный пользователь не может создать заказ')\n    def test_create_order_for_unauthorized_user_fail(self, ingredients_list):\n        create_order = CreateOrders()\n        payload = {\n            'ingredients': ingredients_list\n        }\n        response = create_order.create_order(\n            payload,\n            None\n        )\n>       assert response.status_code == 401\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\orders\\test_create_orders.py:20: AssertionError"}, "start": 1714571199094, "stop": 1714571199477, "uuid": "c1902c3e-f320-443d-b478-69bbc222ff9f", "historyId": "94922073c031cd9d9b4cc134b5c5fd84", "testCaseId": "94922073c031cd9d9b4cc134b5c5fd84", "fullName": "tests.orders.test_create_orders.TestCreateOrders#test_create_order_for_unauthorized_user_fail", "labels": [{"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_create_orders"}, {"name": "subSuite", "value": "TestCreateOrders"}, {"name": "host", "value": "DESKTOP-HCED1QB"}, {"name": "thread", "value": "54684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_create_orders"}]}